name: 15-minute-cron
on:
  schedule:
    - cron: '0 50 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://dao-inspector-server-beatercode.vercel.app/run'